-- Easydent migratie 004: Dein Dental praktijken (37 vestigingen)
-- Voer uit via phpMyAdmin

INSERT INTO practices (name, city, country, language, email, phone) VALUES
('Ingelheim am Rhein',      'Ingelheim am Rhein',    'DE', 'DE', 'info@zahnarztpraxis-ingelheim.de',       '06132 717676'),
('Lindau',                  'Lindau',                 'DE', 'DE', 'praxis-lindau@dein-dental.de',           '08382 72528'),
('Tegernsee',               'Tegernsee',              'DE', 'DE', 'praxis@dr-marquardt.de',                 '08022 1505'),
('Berchtesgaden',           'Berchtesgaden',          'DE', 'DE', 'anmeldung@dr-budzisch.de',               '08652 2859'),
('Karlsruhe',               'Karlsruhe',              'DE', 'DE', 'praxis-karlsruhe@dein-dental.de',        '0721 1208370'),
('Neu-Ulm',                 'Neu-Ulm',                'DE', 'DE', 'praxis-neu-ulm@dein-dental.de',          '0731 140120'),
('Unterhaching',            'Unterhaching',           'DE', 'DE', 'praxis-unterhaching@dein-dental.de',     '089 66509761'),
('Kirn',                    'Kirn',                   'DE', 'DE', 'kirn@dein.dental',                       '06752 9145420'),
('Mönchengladbach',         'Mönchengladbach',        'DE', 'DE', 'info@baatz-zahnaerzte.de',               '02161 5764747'),
('Goch',                    'Goch',                   'DE', 'DE', 'praxis-goch@dein-dental.de',             '02823 6051'),
('München Am Mira',         'München',                'DE', 'DE', 'praxis-am-mira@dein-dental.de',          '089 37499420'),
('Augsburg',                'Augsburg',               'DE', 'DE', 'praxis-augsburg@dein-dental.de',         '0821 207583'),
('Simmern',                 'Simmern',                'DE', 'DE', 'simmern@dein.dental',                    '06761 7979'),
('Rüdesheim',               'Rüdesheim',              'DE', 'DE', 'ruedesheim@dein.dental',                 '0671 42052'),
('Bad Kreuznach',           'Bad Kreuznach',          'DE', 'DE', 'bad.kreuznach@dein.dental',              '0671 30647'),
('Brauweiler',              'Pulheim',                'DE', 'DE', 'praxis-brauweiler@dein-dental.de',       '02234 81818'),
('Ludwigshafen',            'Ludwigshafen am Rhein',  'DE', 'DE', 'praxis-ludwigshafen@dein-dental.de',    '0621 512952'),
('Alzey',                   'Alzey',                  'DE', 'DE', 'alzey@dein.dental',                      '06731 61880'),
('Mannheim',                'Mannheim',               'DE', 'DE', 'praxis-mannheim@dein-dental.de',         '0621 78998090'),
('Westhofen',               'Westhofen',              'DE', 'DE', 'westhofen@dein.dental',                  '06244 4744'),
('Moers',                   'Moers',                  'DE', 'DE', 'info@zahnmoers.de',                      '02841 888780'),
('Koblenz',                 'Koblenz',                'DE', 'DE', 'praxis@dental-fit.de',                   '0261 9738160'),
('Mülheim an der Ruhr',     'Mülheim an der Ruhr',   'DE', 'DE', 'praxisklinik-muelheim@dein-dental.de',   '0208 751305'),
('Dortmund',                'Dortmund',               'DE', 'DE', 'praxis@dr-grebe.de',                     '0231 524279'),
('Stammham',                'Stammham',               'DE', 'DE', 'stammham@reinthaler-hagn.de',            '08405 924979'),
('Lünen',                   'Lünen',                  'DE', 'DE', 'praxis@dr-grebe.de',                     '02306 6600'),
('Papenburg',               'Papenburg',              'DE', 'DE', 'info@zahnimplantate-emsland.de',         '04961 668550'),
('Gössenheim',              'Gössenheim',             'DE', 'DE', 'praxis-goessenheim@dein-dental.de',      '09358 208'),
('Osnabrück',               'Osnabrück',              'DE', 'DE', 'info@zahnarzt-schneider-osnabrueck.de',  '0541 25694'),
('Medebach',                'Medebach',               'DE', 'DE', 'info@zahnarzt-medebach.de',              '02982 92940'),
('Weiden in der Oberpfalz', 'Weiden in der Oberpfalz','DE', 'DE', 'email@geymeier.de',                     '0961 21222'),
('Rotenburg',               'Rotenburg',              'DE', 'DE', 'info@zahnarzt-rotenburg.de',             '04261 974411'),
('Berlin',                  'Berlin',                 'DE', 'DE', 'wittenau@medentes.de',                   '030 4111247'),
('Buxtehude',               'Buxtehude',              'DE', 'DE', 'praxis-buxtehude@dein-dental.de',        '04161 512233'),
('Hannover Georgspalast',   'Hannover',               'DE', 'DE', 'gop@dein-dental.de',                     '0511 326252'),
('Hannover Lister Platz',   'Hannover',               'DE', 'DE', 'praxis-listerplatz@dein-dental.de',      '0511 669120'),
('Solingen',                'Solingen',               'DE', 'DE', 'praxis-solingen@dein-dental.de',         '0212 201309');
